namespace CatchUpPlatform.API.News.Interfaces.REST.Resources;

/// <summary>
/// Resource to create a favorite source 
/// </summary>
/// <param name="NewsApiKey">The News API Key generated by the news provider</param>
/// <param name="SourceId">The news provider source ID</param>
public record CreateFavoriteSourceResource(string NewsApiKey, string SourceId);